import { Link } from '../router';
import { SitePage } from './SiteLayout';

const SOURCES: [string, string, string][] = [
  ['WindNinja', 'US Forest Service, Missoula Fire Sciences Laboratory', 'https://github.com/firelab/windninja'],
  ['HRRR forecast', 'NOAA, via NOMADS (downloaded by WindNinja)', 'https://rapidrefresh.noaa.gov/hrrr/'],
  ['Hourly weather', 'Open-Meteo', 'https://open-meteo.com'],
  ['Elevation, US', 'USGS 3D Elevation Program (3DEP), via py3dep', 'https://www.usgs.gov/3d-elevation-program'],
  ['Elevation, elsewhere', 'Copernicus GLO-30 DEM, ESA / Airbus', 'https://spacedata.copernicus.eu'],
  ['Land cover, US', 'NLCD 2021, USGS / MRLC', 'https://www.mrlc.gov'],
  ['Land cover, elsewhere', 'ESA WorldCover 2021', 'https://esa-worldcover.org'],
  ['Trails, roads, streams', '© OpenStreetMap contributors (ODbL), via the Overpass API', 'https://www.openstreetmap.org/copyright'],
  ['Place search', 'OpenStreetMap Nominatim', 'https://nominatim.org'],
  ['Base maps', 'OpenTopoMap (CC-BY-SA), USGS The National Map, OpenStreetMap', 'https://opentopomap.org'],
  ['Distance statistics', 'R. Koester, Lost Person Behavior', 'https://www.dbs-sar.com'],
];

export function About() {
  return (
    <SitePage>
      <article className="prose-site mx-auto max-w-prose px-4 py-12">
        <p className="eyebrow !mb-1">About</p>
        <h1 className="font-display text-5xl font-bold leading-none text-ink">About Scent Cone</h1>
        <p className="mt-5 !text-lg">
          Scent Cone started as a two-day hackathon question: if you know roughly where a missing person is, and you know the wind, where should the air-scent dogs go first?
        </p>
        <p>
          Searchers already map where a person is likely to be. Dogs, though, find scent, and scent is wherever the air carries it. In hill country that changes through the day as
          slopes warm and cool. Scent Cone joins a lost-person probability map, the Forest Service&apos;s WindNinja wind model and a simple scent simulation, so a planner can see where
          a dog has the best chance and when.
        </p>

        <h2>Status</h2>
        <p>
          A working prototype. The terrain, land cover and wind come from real data and established models. The scent behaviour is a set of rules of thumb, chosen to be reasonable and
          documented in full on <Link to="/how-it-works">How it works</Link>. It has not been tested against field trials.
        </p>
        <div className="not-prose my-6 rounded border-l-4 border-sar bg-white px-4 py-3 text-[15px] leading-relaxed text-ink">
          <strong>Not for operational use.</strong> Scent Cone is meant to support a conversation with experienced K9 handlers and search managers. It does not replace their judgement,
          an incident command structure, or local knowledge.
        </div>

        <h2>Data sources and credits</h2>
        <table>
          <thead>
            <tr>
              <th>What</th>
              <th>Source</th>
            </tr>
          </thead>
          <tbody>
            {SOURCES.map(([what, who, url]) => (
              <tr key={what}>
                <td className="whitespace-nowrap font-medium">{what}</td>
                <td>
                  <a href={url}>{who}</a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <h2>Source code</h2>
        <p>
          Everything, including the model parameters, the backend and the script that builds the demo data, is at{' '}
          <a href="https://github.com/Chr1spu/scent-cone">github.com/Chr1spu/scent-cone</a>. The 3D models are generated by a script in the repository.
        </p>
      </article>
    </SitePage>
  );
}

export function NotFound() {
  return (
    <SitePage>
      <div className="mx-auto max-w-prose px-4 py-24">
        <p className="eyebrow">404</p>
        <h1 className="mt-2 font-display text-4xl font-bold">This page is off the map.</h1>
        <p className="mt-3 text-ink-2">
          Try the <Link to="/">home page</Link> or <Link to="/planner?demo">open the demo</Link>.
        </p>
      </div>
    </SitePage>
  );
}
